name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      run: aws elasticbeanstalk create-application-version --application-name twit --version-label v2 --source-bundle S3Bucket=elasticbeanstalk-eu-west-1-424370049144,S3Key=https://elasticbeanstalk-eu-west-1-424370049144.s3.eu-west-1.amazonaws.com/1712959703603-twit-main.zip && aws elasticbeanstalk update-environment --application-name twit --environment-name twit-env --version-label v2
