name: deploy-eu-west-1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      run: COMMIT_ID=$(git rev-parse --short HEAD) aws elasticbeanstalk create-application-version --application-name twit --version-label v2 --source-bundle GitHub={Repository="amoweolubusayo/twit",CommitId="$COMMIT_ID"} && aws elasticbeanstalk update-environment --application-name twit --environment-name twit-env --version-label v2



