# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies for api project
      run: dotnet restore Twit.WebAPI/Twit.WebAPI.csproj

    - name: Build
      run: dotnet build Twit.WebAPI/Twit.WebAPI.csproj --no-restore

    - name: Test
      run: dotnet test Twit.WebAPI/Twit.WebAPI.csproj --no-build --verbosity normal

    - name: Restore dependencies for core project
      run: dotnet restore Twit.Core/Twit.Core.csproj

    - name: Build
      run: dotnet build Twit.Core/Twit.Core.csproj --no-restore

    - name: Test
      run: dotnet test Twit.Core/Twit.Core.csproj --no-build --verbosity normal

    - name: Restore dependencies for infrastructure project
      run: dotnet restore Twit.Infrastructure/Twit.Infrastructure.csproj

    - name: Build
      run: dotnet build Twit.Infrastructure/Twit.Infrastructure.csproj --no-restore

    - name: Test
      run: dotnet test Twit.Infrastructure/Twit.Infrastructure.csproj --no-build --verbosity normal

    - name: Restore dependencies for test project
      run: dotnet restore Twit.Test/Twit.Test.csproj

    - name: Build
      run: dotnet build Twit.Test/Twit.Test.csproj --no-restore

    - name: Test
      run: dotnet test Twit.Test/Twit.Test.csproj --no-build --verbosity normal

